service:
  name: fraud-check
  description: Fraud Check API
  version: 0.0.1
  url:
    base: /api/v1
    docs: /doc

services:
  fraudAway:
    path: '{{FRAUD_AWAY_PATH}}'
    timeout: '{{FRAUD_AWAY_TIMEOUT}}'
  simpleFraud: 
    path: '{{SIMPLE_FRAUD_PATH}}'
    timeout: '{{SIMPLE_FRAUD_TIMEOUT}}'

threshold:
  risk_score: '{{RISK_SCORE}}'
  bypass_amount: '{{BYPASS_AMOUNT}}'

logger:
  http: false
