service:
  name: fraud-check
  description: Fraud Check API
  version: 0.0.1
  url:
    base: /api/v1
    docs: /doc

server:
  host: localhost
  port: 3000

security:
  docs:
    username: {{DOCS_USERNAME}}
    password: {{DOCS_PASSWORD}}

services:
  fraudAway:
    path: '{{FRAUD_AWAY_PATH}}'
    timeout: '{{FRAUD_AWAY_TIMEOUT}}'
  simpleFraud: 
    path: '{{SIMPLE_FRAUD_PATH}}'
    timeout: '{{SIMPLE_FRAUD_TIMEOUT}}'

logger:
  http: false
